### ISSUE TITLE
Sildes from PyCon tutorial

### ISSUE THREAD

**Issue by aterrel** [WolframAlph/pointers-in-python#1]
@WolframAlph I'm trying to refollow the lessons from the tutorial last week with better internet. Are the slides available anywhere?

**Comment by WolframAlph** [comment]
Hi @aterrel , I have uploaded presentation to us.pycon.org. Are you able to find it there?

**Comment by aterrel** [comment]
No I don't see them anywhere on us.pycon.org

Is there an area of the site that has presentations?

**Comment by WolframAlph** [comment]
So I see something like this:
<img width="1023" alt="Screenshot 2024-05-25 at 17 21 05" src="https://github.com/WolframAlph/pointers-in-python/assets/46005801/985966fb-68a7-4e9d-9b05-d0a345b88102">

Im assuming that all attendees of my workshop can view whatever I put there

**Comment by aterrel** [comment]
I attended the workshop and I don't see it. Is there a reason to not put it here in this repository or on speakerdeck?

**Comment by WolframAlph** [comment]
Hi @aterrel , sorry for late response. Here is recording of that session: https://www.youtube.com/watch?v=YepFiwhK3d8&t=766s&ab_channel=PyConUS . Would that be enough or you still want slides uploaded?

**Comment by aterrel** [comment]
I see the [slide link](https://pycon-assets.s3.amazonaws.com/2024/media/presentation_slides/80/2024-05-25T08%3A34%3A17.223246/Pointers_in_Python.pdf) in the description. Thanks!
